# Generated by Django 3.2.7 on 2025-12-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
