# Generated by Django 3.2.7 on 2025-12-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_app', '0002_user_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='principal',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
