# Generated by Django 3.2.7 on 2025-12-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_app', '0004_aiclarificationlog_course_exam_proctoringlog_result_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='creation_method',
            field=models.CharField(choices=[('Manual', 'Manual'), ('AI', 'AI Generated')], default='Manual', max_length=10),
        ),
    ]
