# Generated by Django 3.2.7 on 2025-12-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_app', '0005_exam_creation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='proctoring_config',
            field=models.TextField(default='{}', help_text="JSON configuration for proctoring settings (e.g., {'camera': true, 'screen': true})"),
        ),
    ]
