# Generated by Django 3.2.7 on 2025-12-18 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality_app', '0006_alter_exam_proctoring_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('SAQ', 'Short Answer Question'), ('EBQ', 'Essay Based Question')], max_length=10)),
                ('options', models.TextField(blank=True, help_text='JSON representation of options for MCQ', null=True)),
                ('answer', models.TextField(help_text='Correct answer or answer key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='quality_app.studymaterial')),
            ],
        ),
    ]
