# Generated by Django 3.2.7 on 2025-12-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_app', '0007_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='Teacher', max_length=100),
        ),
    ]
