# Generated by Django 3.2.7 on 2026-01-01 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality_app', '0008_teacher_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quality_app.exam'),
        ),
        migrations.AlterField(
            model_name='question',
            name='study_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_questions', to='quality_app.studymaterial'),
        ),
    ]
