# Generated by Django 3.2.7 on 2026-01-01 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality_app', '0009_auto_20260101_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Snapshot of question text in case Question is deleted')),
                ('student_answer', models.TextField()),
                ('ai_score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality_app.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quality_app.result')),
            ],
        ),
    ]
