# Generated by Django 3.2.7 on 2026-01-02 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality_app', '0011_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiclarificationlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_app.student'),
        ),
        migrations.AlterField(
            model_name='proctoringlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_app.student'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_app.student'),
        ),
    ]
